import React from 'react'
import styles from './page31.module.scss'

const Page31 = () => {
  return (
    <div className={styles.wrapper}>
      <p className={styles.text7}>MASON NYSTROMri</p> 
      <p className={styles.text8}>MESSARI </p> 
      <img src="/magazine/3/images/35_36/image7.png" className={styles.image9}/>
      <img src="/magazine/3/images/35_36/image6.png" className={styles.image8}/>
      <p className={styles.text9}>My foreway into crypto started in 2017 when I worked for a local cryptocurrency exchange in Hong Kong. Unlike many other early crypto enthusiasts, I don’t come from a finance background and was naturally more interested in cryptonetworks that aimed at solving problems outside of finance. As I continued my career at ConsenSys and then Messari, this interest naturally led me to dive deeper into companies building out the infrastructure for Web3, NFTs, DAOs, and other types of consumer applications.</p> 
      <p className={styles.text13}><span className={styles.text14}>What does the future look like for content creators in web3? It’s often described as the ownership economy, but what is that actually?</span>
<br/><br/>
The existing Web is comprised of networks or companies that leverage creators for their products. Early on, these networks or companies like Medium acted as aggregators and provided creators distribution. But distribution is no longer enough of a value proposition for content creators. That’s why Substack has been so successful, because it enables writers to more effectively monetize their work. For example, the top writers on Medium might make $100,000 per year while the top writers on Substack make millions per year. But even Substack limits the upside of creators because it’s the creators that create the value. Web3 is the transition to giving content creators more equity or ownership in the networks they make valuable. To continue the analogy, a Web3 substack would be one in which writers earned equity for the value they provide to substack or artists earned equity/stock in Spotify based on the users they bring to the platform. Web3 removes some of the middlemen on existing content platforms and provides greater upside to the artists. Another key aspect of Web3 is that it enables royalties to more effectively pass through to creators which means creators benefit financially from the lifetime of their work, not just the initial sale. </p> 
      <p className={styles.text15}><span className={styles.text16}>How is content valued in the ownership economy, how do people actually evaluate natively digital assets ie. the metadata of an NFT? </span>
<br/><br/>
The continued growth of crypto is coinciding with a shift in how people perceive value. The best illustration of this shift in value comes from Gen Z and Fortnite. Gaming “skins” (digital clothes) and emotes (actions) are a multi-billion dollar industry for items inside games that provide zero utility value. Fortnite skins and emotes don’t make players jump higher, run faster, or improve the game experience in any way, yet users spend billions of dollars a year. Couple this shift with digitally native ways to transfer and create value (e.g. digital assets on blockchains) and it unlocks enormous potential. As far as how these natively digital assets are value, some are based on perception, others will be valuable because of the utility they provide. Metadata will be increasingly important. The U.S government kills people based on metadata. NFTs and other digital assets will create more metadata on-chain that can be used and parsed to derived social value (e.g. Jay Z once owned this album before). As metadata becomes more prevalent, it will be increasingly valuable both in terms of its predictive value and its social value.</p> 
      <p className={styles.text17}><span className={styles.text18}>What’s the role of a DAO in the ownership economy and how should creators be interacting with DAOs and be able to elevate themselves but also interactions within web3 through them?</span>
<br/><br/>
DAOs are simply a way that individuals can come together to organize, similar to how a group of individuals might create a company. While DAOs are quite rudimentary today, they will become more efficient than existing companies due to their digitally native structures, the open tooling, and ability to evolve at a faster pace. Creators can interact with DAOs as contractors or join DAOs where they feel an aligned mission. As Web3 continues to evolve, DAOs will become the standard organizational structure for group work and collective action.</p> 
      <p className={styles.text21}><span className={styles.text22}>How do we onboard the next billion people into Web3? Specifically creators; how do we give them a platform, resources, tools for achieving greater financial success? How do we serve their needs? And really do it, not just talk about the tech behind it?</span>
<br/><br/>
When people in crypto discuss the benefits of permissionless blockchains they always start by advocating the benefits of decentralization where instead they should focus on the financial benefits that are available. Today, Web3 is still building out key infrastructure, creator monetization is not standardized, and isn’t as easy to use as existing counterparts. However, as Web3 becomes more seamless, creators will naturally shift towards these platforms because they will have an enormous financial upside compared to the legacy platforms. Writers moved from Medium to Substack because they wanted more money. The first writers who moved faced the most significant risk, but also received the greatest upside. The same dynamic lies true for all of crypto and Web3, the first individuals that move will bear the largest burden, but if successful, will benefit disproportionately to those who lag behind. </p> 
    </div>
  )
}

export default Page31