export const DIGITAL_CHANGING_ROOM = 'Indie Digital & Physical Fashion Changing Room'
export const DIGIFIZZY_BUNDLES = 'DIGIFIZZY BUNDLES'
export const DRIP_IDL = 'DRIP IRL'
export const GENESIS_MONA_NFT = 'GENESIS MONA NFT'
export const LOOK_FASHION_LOOT = 'LOOK FASHION LOOT'
export const PODE = 'PODE'
export const GDN_MEMBERSHIP_NFT = 'GDN MEMBERSHIP NFT'