const details = [
  [
    {
      id: 1,
      title: 'Common Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/common/Untitled (24).mp4',
        '/images/nft/1/common/Untitled (20).mp4',
        '/images/nft/1/common/gamer-girl.jpg',
        '/images/nft/1/common/Project Name (2).mp4',
        '/images/nft/1/common/Untitled (2).mp4',
        '/images/nft/1/common/Untitled (28).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl gamer trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion jewellery collectible, electronic bass audio tune from top San Francisco based music artist Singe, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 2,
      title: 'Semi-Rare Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/semi/Untitled (23).mp4',
        '/images/nft/1/semi/Untitled (21).mp4',
        '/images/nft/1/semi/Angel-with-rose.jpg',
        '/images/nft/1/semi/Project Name (1).mp4',
        '/images/nft/1/semi/Untitled (4).mp4',
        '/images/nft/1/semi/Untitled (27).mp4',
        '/images/nft/1/semi/1.gif',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl angel trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible male outfit, melodic audio  tune from top San Francisco based DJ J-Kind, physical DIGITALAX DRIP fashion item with on-chain utility, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 3,
      title: 'Exclusive Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/exc/Untitled (25).mp4',
        '/images/nft/1/exc/Cameron (1).png',
        '/images/nft/1/exc/girl-and-panda.png',
        '/images/nft/1/exc/HARUTO (1).png',
        '/images/nft/1/exc/James (1).png',
        '/images/nft/1/exc/Project Name (3).mp4',
        '/images/nft/1/exc/Untitled (15).mp4',
        '/images/nft/1/exc/VICtor.png',
        '/images/nft/1/exc/3.gif',
        '/images/nft/1/exc/Untitled (26).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl rare trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible female outfit, synth audio tune from renowned San Francisco based music veteran Gregory Gordon, physical DIGITALAX DRIP fashion item with on-chain utility, Web3 Wizards Genesis collection, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 5,
      title: 'Common Unlock',
      subTitle: [
        'Issue Two',
        'PORTAL',
        'Edge Outfit',
        'MC OG 1.5',
        'Wear Your Values HRF Leap of Faith: Courage',
        'Minecraft Guild Hoodie Orange',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/common/moshed-06-11-5-3-53.mp4',
        '/images/nft/2/common/1080p (1).MOV',
        '/images/nft/2/common/Digitalax_02.mp4',
        '/images/nft/2/common/espa_skin (1).mp4',
        '/images/nft/2/common/Untitled.mp4',
        '/images/nft/2/common/MC-Gif (1).gif',
        '/images/nft/2/common/IMG_202105281404040 (3).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `9EN travels through different dimensions, virtual realms, and eventually makes it to Earth. A portal she uses through hyperspace travel is a symbol portrayed in this particular NFT. The symbol tends to stretch out due to a gravitational singularity in which there's a chaotic oscillation of the stretching and squeezing of space during an interstellar journey. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `This outfit stands out for its angular and metallic lines. It's a flashy evening urban style. The jacket is semi-rigid and the trousers are sporty. On the trousers there are two bands that recall the jacket's details. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `A one of its kind Minecraft digital fashion skin designed by a dude that's been at the heart of the game for more than a decade. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network. `,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 6,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Two',
        'SEE',
        'Porka Jacket',
        'Wear Your Values HRF Leap of Faith: All In',
        'Polaris X35 Suit',
        'Minecraft Guild Hoodie Green',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/semi/moshed-06-11-5-12-59.mp4',
        '/images/nft/2/semi/Video_1 (2).MOV',
        '/images/nft/2/semi/Untitled (3).png',
        '/images/nft/2/semi/Untitled (1).mp4',
        '/images/nft/2/semi/Polaris-suit-x35-digitalax.png',
        '/images/nft/2/semi/MC-Gif (1) copy 2.gif',
        '/images/nft/2/semi/IMG_202105281404040 (3).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `9EN is seen to be approaching a symbol she's curious to know more about. Her first encounter with the symbol feels like a magnetic effect that's pulling her closer and closer. She enters the portal. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `Designed by Nicole Savitskaya, a talented digital fashion designer from Ukraine and the founder of porka_x. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `Designed by Mia Locklace and modeled by Sarah Reikka, a French Canadian virtual influencer & model. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 7,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Two',
        'Wear Your Values HRF Leap of Faith: Cross Over',
        'SAVAGE',
        'Welcome to the Meta-Jungle',
        'Lumps',
        'Minecraft Guild Hoodie Purple',
        'Alex Beregszaszi',
        'Pooja Ranjan',
        'Abdelhamid Bakhta',
        'Tim Beiko',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/exc/moshed-06-11-5-24-5.mp4',
        '/images/nft/2/exc/Untitled (2).mp4',
        '/images/nft/2/exc/720p.MOV',
        '/images/nft/2/exc/BladeRunway Final Render HD (1).png',
        '/images/nft/2/exc/Animation.mp4',
        '/images/nft/2/exc/MC-Gif (1) copy.gif',
        '/images/nft/2/exc/Alex (1).png',
        '/images/nft/2/exc/Pooja (1).png',
        '/images/nft/2/exc/Abdel Hamid (1).png',
        '/images/nft/2/exc/Tim Beiko (1).png',
        '/images/nft/2/exc/IMG_202105281404040 (2).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content, Web3 Wizards collectible series + access to unlockable magazine content pages.`,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `When 9EN is traveling through the virtual realms of the Earth she stumbles upon a song called 'Savage' by Megan Thee Stallion. This NFT presents a tunnel trip featuring 'Savage' remixed by 9EN. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `Blade Runway is the first Digital Couture Fashion House in Italy. Founded by designers Greta Meacci and Alan Aronica, the project was launched to bring the high quality and know-how of traditional Italian haute couture into the digital world. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Lumps is a wearable living creature. She was created on a different planet using the natural resources from this planet's environment. Similar to how a plant on earth is an actual living organism, the plants on this planet are alive and possess different capabilities. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
];

export default details;
