export const details = [
  [
    {
      id: 30,
      title: 'Common Unlock',
      subTitle: [
        'Issue Six',
        'Meta Glitch DRIP T-Shirt',
        'Dreams of Disconnection by SquintDev',
        'Reactor Upgrade by Ben Roberts',
        'Ensnared by Dawnia Darkstone aka Letsglitchit',
        'Ancestral Smile by Suliman',
        'New Heights by Hugo Alves',
        'State of Growth I by Professor-Wrecks',
      ],
      issueIndex: 'Issue Six',
      url: [
        '/images/nft/6/common/metaverse_medici_couture.mp4',
        '/images/nft/6/common/1.gif',
        '/images/nft/6/common/dreams-of-disconnection - Tom Duffy.png',
        '/images/nft/6/common/20190413_221507 - Astro Biological (1).mp4',
        '/images/nft/6/common/Ensared - Dawnia Darkstone.png',
        '/images/nft/6/common/77839934-2CFA-47EC-B9EB-16319D38EE93 - Suliman Onque.jpeg',
        '/images/nft/6/common/new heights - Hugo Alves tattoo (2).jpg',
        '/images/nft/6/common/State of Growth gif by Wrecks - R. NawlsWalker (1).gif',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; in-house designed IRL DRIP glitch T-shirt and a unique collection of artist features from the Screensaver World community, including art from SquintDev, Ben Roberts, Dawnia Darkstone aka Letsglitchit, Suliman, Hugo Alves and Professor-Wrecks.',
        'IRL DRIP T-Shirt. Glitching harder and more often— these metaversal digicore vibes are keeping my street cred.  Stake the 721 NFT for $MONA yield. You’ll be sent an email upon purchase guiding you on how to process all shipment details. You’ll also be sent a 721 stackable version of the NFT upon placing the IRL order. ',
        'This piece represents my subconscious desire to disconnect from everything and everyone and just isolate. By creating pieces like this, it helps me stay self-aware that my thinking can go in this direction and I can be vigilant about it. I am SquintDev, a digital artist and software developer from Reno, NV. I got into the NFT world back in April and it has been amazing. The community surrounding Screensaver has become like a family to me.'
        "A mysterious machine appears in the city. It is opening a doorway to somewhere.... Hi, my name is Ben Roberts. I'm  an Australian digital artist, focussing on smartphone and tablet based art apps on the Android ecosystem. In terms of the art space, I describe myself as an independent solo artist, exploring almost any theme that comes into my head, I get bored easily, and will always be working on the new and the different!'
        'A classic (2016) Letsglitchit. FBX format 3D glitch. Dawnia Darkstone, AKA Letsglitchit (she/they) has been at the forefront of brute force, non-coding based glitch art for close to 10 years. She is co-administrator of Glitch Artists Collective and affiliated groups on Facebook and has been exhibited in London, Paris, Zagreb, San Francisco, Minneapolis, and her novel work with sonification has been featured in Vice Magazine.'
        'Colorful abstract painting of smiling  tribesmen, with an orange sun behind them. I’m a visual artist and muralist from Newark Nj, USA . My motto is, If you can imagine it, I can create it…Artistically.'
        "This piece is a mark of improvement of the artistic skills, it symbolizes the path to get where you want to go, I did this piece in a particular moment where I was stuck in place, I was stopping myself from growing artistically, so I made this piece to remind me where I can get to if I study and don't stop there, I'm glad I did, that's why the astronaut on the moon, as a small step for man, but a giant leap for mankind, and the constellations in the sky spelling new heights, so I can forever remember to keep going. I'm Hugo, a tattoo, digital and traditional artist in Brazil, I study mostly classic illustration to be able to find my style among so much good stuff. The NFTworld helped me a lot to find my path in art."
        'I am in a constant space of learning and unlearning. I am a Musician, digital artists & founder of shrug city media; a Chicago based, specializing in dance music + 3D/Text based art production.'
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 31,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Six',
        'Meta Glitch DRIP T-Shirt',
        'Dreams of Disconnection by SquintDev',
        'Reactor Upgrade by Ben Roberts',
        'Ensnared by Dawnia Darkstone aka Letsglitchit',
        'Ancestral Smile by Suliman',
        'New Heights by Hugo Alves',
        'State of Growth I by Professor-Wrecks',
        'Death of a Narcissist by Deported Photographer',
        'Naked Prince by ohmyelijah',
        'Dark Mandala by The Philosopher',
        'Portrait of a self-portrait in a portrait by vocesferales',
        'Viva a natureza by Aumm das Cripto',
        'bitmap painting sequence [비트맵 페인팅 시퀀스] by Blu Simon Wasem',
      ],
      issueIndex: 'Issue Six',
      url: [
        '/images/nft/6/semi/moshed-10-20-3-53-8.mp4',
        '/images/nft/6/common/1.gif',
        '/images/nft/6/common/dreams-of-disconnection - Tom Duffy.png',
        '/images/nft/6/common/20190413_221507 - Astro Biological (1).mp4',
        '/images/nft/6/common/Ensared - Dawnia Darkstone.png',
        '/images/nft/6/common/77839934-2CFA-47EC-B9EB-16319D38EE93 - Suliman Onque.jpeg',
        '/images/nft/6/common/new heights - Hugo Alves tattoo (2).jpg',
        '/images/nft/6/common/State of Growth gif by Wrecks - R. NawlsWalker (1).gif',
        '/images/nft/6/semi/26180_mirror4 - Deported Photographer (1).jpg',
        '/images/nft/6/semi/84620016 - Elijah Negasi (1).jpeg',
        '/images/nft/6/semi/Abstract 8 (2) - rodrigo cid (1).png',
        '/images/nft/6/semi/PortraitofaselfportraitinaportraitByVocesferales-1 - Hilandera (1).jpg',
        '/images/nft/6/semi/IMG_5777 - julia (1).PNG',
        '/images/nft/6/semi/Design sem nome (32) (1) (1).gif',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; in-house designed IRL DRIP glitch t-shirt and a unique collection of artist features from the Screensaver World community, including art from SquintDev, Ben Roberts, Dawnia Darkstone aka Letsglitchit, Suliman, Hugo Alves, Professor-Wrecks, Deported Photographer, Mx Spite, ohmyelijah, The Philosopher, vocesferales, Isaiah Lemmon, Aumm das Cripto and Blu Simon Wasem.',
        'IRL DRIP T-Shirt. Glitching harder and more often— these metaversal digicore vibes are keeping my street cred.  Stake the 721 NFT for $MONA yield. You’ll be sent an email upon purchase guiding you on how to process all shipment details. You’ll also be sent a 721 stackable version of the NFT upon placing the IRL order. ',
        'This piece represents my subconscious desire to disconnect from everything and everyone and just isolate. By creating pieces like this, it helps me stay self-aware that my thinking can go in this direction and I can be vigilant about it. I am SquintDev, a digital artist and software developer from Reno, NV. I got into the NFT world back in April and it has been amazing. The community surrounding Screensaver has become like a family to me.'
        "A mysterious machine appears in the city. It is opening a doorway to somewhere.... Hi, my name is Ben Roberts. I'm  an Australian digital artist, focussing on smartphone and tablet based art apps on the Android ecosystem. In terms of the art space, I describe myself as an independent solo artist, exploring almost any theme that comes into my head, I get bored easily, and will always be working on the new and the different!'
        'A classic (2016) Letsglitchit. FBX format 3D glitch. Dawnia Darkstone, AKA Letsglitchit (she/they) has been at the forefront of brute force, non-coding based glitch art for close to 10 years. She is co-administrator of Glitch Artists Collective and affiliated groups on Facebook and has been exhibited in London, Paris, Zagreb, San Francisco, Minneapolis, and her novel work with sonification has been featured in Vice Magazine.'
        'Colorful abstract painting of smiling  tribesmen, with an orange sun behind them. I’m a visual artist and muralist from Newark Nj, USA . My motto is, If you can imagine it, I can create it…Artistically.'
        "This piece is a mark of improvement of the artistic skills, it symbolizes the path to get where you want to go, I did this piece in a particular moment where I was stuck in place, I was stopping myself from growing artistically, so I made this piece to remind me where I can get to if I study and don't stop there, I'm glad I did, that's why the astronaut on the moon, as a small step for man, but a giant leap for mankind, and the constellations in the sky spelling new heights, so I can forever remember to keep going. I'm Hugo, a tattoo, digital and traditional artist in Brazil, I study mostly classic illustration to be able to find my style among so much good stuff. The NFTworld helped me a lot to find my path in art."
        'I am in a constant space of learning and unlearning. I am a Musician, digital artists & founder of shrug city media; a Chicago based, specializing in dance music + 3D/Text based art production.'
        "Even in death the narcissist will look at their reflection for eternity. DREAMER turned drug dealer State penitentiary alum Parolee Photographer & Deportee I once walked 15hrs through Arizona desert to come home... It's been a crazy ride! Now I’m a father who cares for 2 little girls with one more on the way. I'm in this space to push NFT photography to new limits and make people reconsider what NFT photography can be. This is all to secure a better future for my family.'
        'Young boy from the Hamer Tribe. I am Elijah Negasi. I am from the Bronx of New York City. I am a filmmaker and photographer, as well as a beat-maker.'
        "Dark Mandala created by The Philosopher to summon demons and undeads. I am a Brazilian Philosophy Professor, Traditional and NFT Artist, Virtual Curator and Gallerist. I was part of many solo and collective physical exhibitions in Rio de Janeiro (BELA Biennial, Fabrica Bhering, Meu BB Galeria), Ouro Preto (GLTA), Brasília (Federal Senate), Macapá (Galeria Trokkal) and Helsinque (AVA Galleria/BELA Biennial). As a curator and gallerist, I made many virtual exhibitions for some communities, like VIBES community, Mintbase community, CriptoArteBR community. As an artist, I work with collage, assemblage, painting, bronze sculpture and digital art. I am also an ambassador from CryptoHamsters NFT-Project, owner from Brazucas NFT Gallery, and owner from multiple wearables stores and have a gallery on Cryptovoxels called The Philosopher's Gallery. I am represented by the traditional AVA Galleria (from Finland) and the virtual gallery Binaria."
        "This is the combination of my most beloved subjects: the objects of the house and the self-portrait, in some sort of inception of images and angles. I'm a Venezuelan photographer and musician. Obsessed with the house and it's objects and with the art of the self-portrait. Trying to push further the limits of the photography conceptually and graphically by digital edition and manipulation.'
        "glitch art created with a digital and analog input, a video mixer, crt tv, captured with sony a6000. footage used from a quake competition and a VHS tape of gigi. I am kway_side, or Isaiah. I'm a disabled photographer who lives in St. Louis. I mainly enjoy street and architecture photography. I'm not really anybody in the art space - kind of unknown. I just like to do art and chill.'
        "My last series on ssw was a collection of bmp files that i sent to myself on the 2nd of december 2013, and i couldn't imagine that it would really become an artwork. It is a form of performative action painting on digital mediums, using the most simple software to create graphics, that can make no sense, but at the same time tell a story, about places, feelings, rests of propaganda, internet trash files. This piece is a gif animation, merging all 22 paintings, at one single file. I’m a mixed media artist from Brazil. I do music, videoart, performance, voxel and 3D glitched objects on different blockchains - near, tezos, polygon, eth - as a crypto artist, I have minted more than 100 NFTs in the past 3 months. Media such as digital videos, audio files, gif animations, still digital painting, and pdf files as a form of artists book.'
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 32,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Six',
        'ET Glitch DRIP T-Shirt',
        'Dreams of Disconnection by SquintDev',
        'Reactor Upgrade by Ben Roberts',
        'Ensnared by Dawnia Darkstone aka Letsglitchit',
        'Ancestral Smile by Suliman',
        'New Heights by Hugo Alves',
        'State of Growth I by Professor-Wrecks',
        'Death of a Narcissist by Deported Photographer',
        'Naked Prince by ohmyelijah',
        'Dark Mandala by The Philosopher',
        'Portrait of a self-portrait in a portrait by vocesferales',
        'Viva a natureza by Aumm das Cripto',
        'bitmap painting sequence [비트맵 페인팅 시퀀스] by Blu Simon Wasem',
        'excuse me by x3r0ne',
        'layered cake by JanusSpans',
        '21st_century_decay.gif by voidkross',
        'A Moment Left by TheGlitchedArts',
        'Natural landscape by Jessytsuki',
        'Rainy Night by Tom Binkiewinkie',
        'Vaporwave is Dead by XWAVE',
        'Dom',
        'Jin Chung',
        'Jacob Horne',
        'Graeme',
      ],
      issueIndex: 'Issue Six',
      url: [
        '/images/nft/6/exc/moshed-10-20-3-53-53.mp4',
        '/images/nft/6/exc/2.gif',
        '/images/nft/6/common/dreams-of-disconnection - Tom Duffy.png',
        '/images/nft/6/common/20190413_221507 - Astro Biological (1).mp4',
        '/images/nft/6/common/Ensared - Dawnia Darkstone.png',
        '/images/nft/6/common/77839934-2CFA-47EC-B9EB-16319D38EE93 - Suliman Onque.jpeg',
        '/images/nft/6/common/new heights - Hugo Alves tattoo (2).jpg',
        '/images/nft/6/common/State of Growth gif by Wrecks - R. NawlsWalker (1).gif',
        '/images/nft/6/semi/26180_mirror4 - Deported Photographer (1).jpg',
        '/images/nft/6/semi/84620016 - Elijah Negasi (1).jpeg',
        '/images/nft/6/semi/Abstract 8 (2) - rodrigo cid (1).png',
        '/images/nft/6/semi/PortraitofaselfportraitinaportraitByVocesferales-1 - Hilandera (1).jpg',
        '/images/nft/6/semi/IMG_5777 - julia (1).PNG',
        '/images/nft/6/exc/post855 - kway_side (1).jpg',
        '/images/nft/6/exc/excuse me - Mark Bender (1).gif',
        '/images/nft/6/exc/Untitled (11).mp4',
        '/images/nft/6/exc/its_only_been5months - Splif Luv.gif',
        '/images/nft/6/exc/Moreso The Lesser - Aaron Stewart (1).jpg',
        '/images/nft/6/exc/Screen Shot 2021-10-20 at 11.17.03 AM.png',
        '/images/nft/6/exc/rainynight - Tomasz Binkiewicz (1).mp4',
        '/images/nft/6/exc/vaporwave is dead-fin - XWAVE Art (1).jpg',
        '/images/nft/6/exc/IMG_0449.PNG',
        '/images/nft/6/exc/IMG_0451.PNG',
        '/images/nft/6/exc/IMG_0448.PNG',
        '/images/nft/6/exc/IMG_0481.PNG',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; in-house designed IRL DRIP glitch t-shirt and a unique collection of artist features from the Screensaver World community, including art from SquintDev, Ben Roberts, Dawnia Darkstone aka Letsglitchit, Suliman, Hugo Alves, Professor-Wrecks, Deported Photographer, Mx Spite, ohmyelijah, The Philosopher, vocesferales, Isaiah Lemmon, Aumm das Cripto, Blu Simon Wasem, x3r0ne, JanusSpans, voidkross, TheGlitchedArts, Jessytsuki, Tom Binkiewinkie and XWAVE and Web3 Wizards collectibles.',
        'IRL DRIP T-Shirt. So much meta that I glitch to another planet— these metaversal digicore vibes are keeping my street cred.  Stake the 721 NFT for $MONA yield. You’ll be sent an email upon purchase guiding you on how to process all shipment details. You’ll also be sent a 721 stackable version of the NFT upon placing the IRL order.',
        'This piece represents my subconscious desire to disconnect from everything and everyone and just isolate. By creating pieces like this, it helps me stay self-aware that my thinking can go in this direction and I can be vigilant about it. I am SquintDev, a digital artist and software developer from Reno, NV. I got into the NFT world back in April and it has been amazing. The community surrounding Screensaver has become like a family to me.'
        "A mysterious machine appears in the city. It is opening a doorway to somewhere.... Hi, my name is Ben Roberts. I'm  an Australian digital artist, focussing on smartphone and tablet based art apps on the Android ecosystem. In terms of the art space, I describe myself as an independent solo artist, exploring almost any theme that comes into my head, I get bored easily, and will always be working on the new and the different!'
        'A classic (2016) Letsglitchit. FBX format 3D glitch. Dawnia Darkstone, AKA Letsglitchit (she/they) has been at the forefront of brute force, non-coding based glitch art for close to 10 years. She is co-administrator of Glitch Artists Collective and affiliated groups on Facebook and has been exhibited in London, Paris, Zagreb, San Francisco, Minneapolis, and her novel work with sonification has been featured in Vice Magazine.'
        'Colorful abstract painting of smiling  tribesmen, with an orange sun behind them. I’m a visual artist and muralist from Newark Nj, USA . My motto is, If you can imagine it, I can create it…Artistically.'
        "This piece is a mark of improvement of the artistic skills, it symbolizes the path to get where you want to go, I did this piece in a particular moment where I was stuck in place, I was stopping myself from growing artistically, so I made this piece to remind me where I can get to if I study and don't stop there, I'm glad I did, that's why the astronaut on the moon, as a small step for man, but a giant leap for mankind, and the constellations in the sky spelling new heights, so I can forever remember to keep going. I'm Hugo, a tattoo, digital and traditional artist in Brazil, I study mostly classic illustration to be able to find my style among so much good stuff. The NFTworld helped me a lot to find my path in art."
        'I am in a constant space of learning and unlearning. I am a Musician, digital artists & founder of shrug city media; a Chicago based, specializing in dance music + 3D/Text based art production.'
        "Even in death the narcissist will look at their reflection for eternity. DREAMER turned drug dealer State penitentiary alum Parolee Photographer & Deportee I once walked 15hrs through Arizona desert to come home... It's been a crazy ride! Now I’m a father who cares for 2 little girls with one more on the way. I'm in this space to push NFT photography to new limits and make people reconsider what NFT photography can be. This is all to secure a better future for my family.'
        'Young boy from the Hamer Tribe. I am Elijah Negasi. I am from the Bronx of New York City. I am a filmmaker and photographer, as well as a beat-maker.'
        "Dark Mandala created by The Philosopher to summon demons and undeads. I am a Brazilian Philosophy Professor, Traditional and NFT Artist, Virtual Curator and Gallerist. I was part of many solo and collective physical exhibitions in Rio de Janeiro (BELA Biennial, Fabrica Bhering, Meu BB Galeria), Ouro Preto (GLTA), Brasília (Federal Senate), Macapá (Galeria Trokkal) and Helsinque (AVA Galleria/BELA Biennial). As a curator and gallerist, I made many virtual exhibitions for some communities, like VIBES community, Mintbase community, CriptoArteBR community. As an artist, I work with collage, assemblage, painting, bronze sculpture and digital art. I am also an ambassador from CryptoHamsters NFT-Project, owner from Brazucas NFT Gallery, and owner from multiple wearables stores and have a gallery on Cryptovoxels called The Philosopher's Gallery. I am represented by the traditional AVA Galleria (from Finland) and the virtual gallery Binaria."
        "This is the combination of my most beloved subjects: the objects of the house and the self-portrait, in some sort of inception of images and angles. I'm a Venezuelan photographer and musician. Obsessed with the house and it's objects and with the art of the self-portrait. Trying to push further the limits of the photography conceptually and graphically by digital edition and manipulation.'
        "glitch art created with a digital and analog input, a video mixer, crt tv, captured with sony a6000. footage used from a quake competition and a VHS tape of gigi. I am kway_side, or Isaiah. I'm a disabled photographer who lives in St. Louis. I mainly enjoy street and architecture photography. I'm not really anybody in the art space - kind of unknown. I just like to do art and chill.'
        "My last series on ssw was a collection of bmp files that i sent to myself on the 2nd of december 2013, and i couldn't imagine that it would really become an artwork. It is a form of performative action painting on digital mediums, using the most simple software to create graphics, that can make no sense, but at the same time tell a story, about places, feelings, rests of propaganda, internet trash files. This piece is a gif animation, merging all 22 paintings, at one single file. I’m a mixed media artist from Brazil. I do music, videoart, performance, voxel and 3D glitched objects on different blockchains - near, tezos, polygon, eth - as a crypto artist, I have minted more than 100 NFTs in the past 3 months. Media such as digital videos, audio files, gif animations, still digital painting, and pdf files as a form of artists book.'
        'gif, 360 x 640 , 8.7mb, 2021. From the series GenFT by x3r0ne. Artist from the US.',
        'visual experiments in overpowering android device glitch processing, massive images were used with glitch apps layered dozens of times, audio from sound sample loops fed into feedback loop experiments from 15 years ago. Old aspiring musician and artist.'
        'GOLDEN LUCK, PENNY HEADS UP. THIS IS AN ARTISTIC STATEMENT TO COMPRESSION, COLOR, DISTORTION, AND PUNK VOIDKROSS_2021. Void K. Ross I am an artist on screensaver.world and in the NFT space ✌️.'
        'Inconsolable even with a fair amount of compensation. I combine abstract/glitch techniques with generative fractals and geometry - Used Pixel Salesman.'
        'You can feel the autumn in the colors and the wind in the strokes of the image, just focus on what catches your attention in this because it has many different points that you can look at and enjoy with what makes you feel, and what you can understand about the composition. I’m jessy, I am a body positive movement artist.'
        "A macro photography of rain drops on flowers during a rainy night. Shows how beautiful nature is from the distance we don't see it, normally. Added animation with Photomosh Pro. It all began a few months ago really. Thanks to NFTs, I started exploring what one can do and how. This way Binkiewinkies' love for macro photography started developing. Long story short, combining photography, AI generated art and animation is something he tries to delve into.'
        'RIP Vaporwave. I’m an American who is compelled to make art. I found CryptoArt when the galleries I used to sell in closed due to Covid. I have a partner I work with a lot and really enjoy the collaborative process.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing some of the core community driven devs in the ecosystem— those that are creating, refining and building for the communities that many of us are intrinsically a part of today. We thank these Community Catalysts as they capitalise that C... in more ways than one.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing some of the core community driven devs in the ecosystem— those that are creating, refining and building for the communities that many of us are intrinsically a part of today. We thank these Community Catalysts as they capitalise that C... in more ways than one.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing some of the core community driven devs in the ecosystem— those that are creating, refining and building for the communities that many of us are intrinsically a part of today. We thank these Community Catalysts as they capitalise that C... in more ways than one.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing some of the core community driven devs in the ecosystem— those that are creating, refining and building for the communities that many of us are intrinsically a part of today. We thank these Community Catalysts as they capitalise that C... in more ways than one. ',
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 27,
      title: 'Common Unlock',
      subTitle: [
        'Issue Five',
        'Golden Choker',
        'Random Walk',
        'Get Dressed 2D Ticket',
        'LOOK Varsity Jacket',
      ],
      issueIndex: 'Issue Five',
      url: [
        '/images/nft/5/common/moshed-09-11-18-29-37.mp4',
        '/images/nft/5/common/Untitled (5).mp4',
        '/images/nft/5/common/JEANS N TOP DJTLX.mp4',
        '/images/nft/5/common/Group 53698.png',
        '/images/nft/5/common/gif-style-2.gif',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Cryptsie 3D digital fashion collectibles, LOOK varsity jacket, Get Dressed 2D Ticket, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'The Golden Choker was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Random Walk was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Get measured by the web3 tailors. Take a look at the menu of what’s in season and tell us how good you want to look. The metaverse awaits your style. This Get Dressed Ticket grants you a 2D fashion design from the Global Designer Network. You will be emailed more details about how you can put through your outfit order! If you choose to include open source patterns, materials or textures, these 1155 NFTs are also linked under the Fractional Garment Ownership standard.',
        'LOOK is a derivative of the Loot project and the first on-chain generative text fashion experiment. Rep this jacket IRL!',
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 28,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Five',
        'Golden Choker',
        'Random Walk',
        'Get Dressed 3D Ticket',
        'LOOK Varsity Jacket',
      ],
      issueIndex: 'Issue Five',
      url: [
        '/images/nft/5/semi/moshed-09-11-18-27-51.mp4',
        '/images/nft/5/common/Untitled (5).mp4',
        '/images/nft/5/common/JEANS N TOP DJTLX.mp4',
        '/images/nft/5/semi/Group 53700.png',
        '/images/nft/5/common/gif-style-2.gif',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Cryptsie 3D digital fashion collectibles, LOOK varsity jacket, Get Dressed 3D Ticket, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'The Golden Choker was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Random Walk was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Get measured by the web3 tailors. Take a look at the menu of what’s in season and tell us how good you want to look. The metaverse awaits your style. This Get Dressed Ticket grants you a 3D fashion design from the Global Designer Network. You will be emailed more details about how you can put through your outfit order! If you choose to include open source patterns, materials or textures, these 1155 NFTs are also linked under the Fractional Garment Ownership standard.',
        'LOOK is a derivative of the Loot project and the first on-chain generative text fashion experiment. Rep this jacket IRL!',
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 29,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Five',
        'Kevin Owocki',
        'Vitalik Buterin',
        'Dan Finlay',
        'Nick Johnson',
        'Golden Choker',
        'Random Walk',
        'Get Dressed 3D + In-Game Ticket',
        'LOOK Varsity Jacket',
      ],
      issueIndex: 'Issue Five',
      url: [
        '/images/nft/5/exc/moshed-09-11-18-32-39.mp4',
        '/images/nft/5/exc/Owocki.png',
        '/images/nft/5/exc/Vitalik.png',
        '/images/nft/5/exc/Dan Finlay.png',
        '/images/nft/5/exc/Nick.png',
        '/images/nft/5/common/Untitled (5).mp4',
        '/images/nft/5/common/JEANS N TOP DJTLX.mp4',
        '/images/nft/5/exc/Group 53701.png',
        '/images/nft/5/common/gif-style-2.gif',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Cryptsie 3D digital fashion collectibles, LOOK varsity jacket, Get Dressed 3D + In-Game Ticket, Web3 Wizards Collectibles, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition of Web3 Wizards we are paying it back to the devs pioneering web3 authentication, decentralised identity management and blockchain native encapsulations of ourselves. These devs are the real Identity Meddlers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition of Web3 Wizards we are paying it back to the devs pioneering web3 authentication, decentralised identity management and blockchain native encapsulations of ourselves. These devs are the real Identity Meddlers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition of Web3 Wizards we are paying it back to the devs pioneering web3 authentication, decentralised identity management and blockchain native encapsulations of ourselves. These devs are the real Identity Meddlers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition of Web3 Wizards we are paying it back to the devs pioneering web3 authentication, decentralised identity management and blockchain native encapsulations of ourselves. These devs are the real Identity Meddlers.',
        'The Golden Choker was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Random Walk was modelled by Global Designer Network member, Cryptsie. My name is Anna, and I am from Crimea - this is a very beautiful region near the Black Sea, with majestic mountains, green valleys and dense forests. I’ve been interested in art since childhood, and when I grew up, there was no doubt about who I wanted to become - of course, a designer.',
        'Get measured by the web3 tailors. Take a look at the menu of what’s in season and tell us how good you want to look. The metaverse awaits your style. This Get Dressed Ticket grants you a 3D fashion design from the Global Designer Network and also a mod in-game compatibility to Minecraft. You will be emailed more details about how you can put through your outfit order! If you choose to include open source patterns, materials or textures, these 1155 NFTs are also linked under the Fractional Garment Ownership standard.',
        'LOOK is a derivative of the Loot project and the first on-chain generative text fashion experiment. Rep this jacket IRL!',
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 21,
      title: 'Common Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        '20 Years of SF Dance Music Christopher Leath Audio NFT',
        '20 Years of SF Dance Music Paul Leath Audio NFT',
        'Winged Glassversarial',
        'Web3 DeFi Fashion Female Collectible',
      ],
      issueIndex: 'Issue Four',
      url: [
        '/images/nft/4/common/Untitled (1) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        'http://digitalax.mypinata.cloud/ipfs/QmZeabmF7EhDnJVHShD8Wgk5zBxNopGsWNU1NyW4qoAvmy',
        '/images/nft/4/common/mindmeld.mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/common/web3girl_allProtocols (1).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket, Web3 DeFi Fashion Female Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music Christopher and Paul Leath Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.',
        'Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and head over to DRIP to purchase the physical varsity jacket version to rep IRL!',
        'Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Christopher Leach aka el gato #9 is a DJ/Producer of various genres Electronic - Techno, DnB, House, Dub, Down-tempo, Dancehall, Ambient, and Experimental.',
        'Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Paul Leath has taken on several roles with his involvement in the electronic community, promoter, agent, manager and record distribution. During this entire span, always producing and deejaying.',
        'The first glass-winged XENOTECH garment.',
        'A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.',
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 22,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        'Collectible 3D Digital Fashion W3FW Bomber Jacket',
        'Web3 DeFi Fashion Male Collectible',
        'Winged Glassversarial',
        '20 Years of SF Dance Music Arturo Mood Audio NFT',
        '20 Years of SF Dance Music Arturo Communication NFT',
      ],
      issueIndex: 'Issue Four',
      url: [
        '/images/nft/4/semi/Untitled (2) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        '/images/nft/4/semi/bomber_digitalax.mp4',
        '/images/nft/4/semi/web3boy_allProtocols.mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/semi/Arturo Garces - Mood.mp4',
        '/images/nft/4/semi/Arturo Garces - Communication.mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket + Digital Fashion 3D Collectible, Web3 DeFi Fashion Male Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music Arturo Garces Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.',
        'Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and head over to DRIP to purchase the physical varsity jacket version to rep IRL!',
        'Unlock the 3D modeled digital fashion W3FW Bomber Jacket version of your Decentraland Skin! A high fidelity version to showcase your style.',
        'A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.',
        'The first glass-winged XENOTECH garment.',
        "Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Arturo's music has helped define the unique and emerging Silicon Valley sound. This approach blends the driving, beat-laden beauty of techno with the soulful, deep melodies of house.",
        "Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Arturo's music has helped define the unique and emerging Silicon Valley sound. This approach blends the driving, beat-laden beauty of techno with the soulful, deep melodies of house.",
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 24,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        'Collectible 3D Digital Fashion W3FW Bomber Jacket',
        'Physical W3FW Varsity Bomber Jacket',
        'Web3 DeFi Fashion Male Collectible',
        'Web3 DeFi Fashion Female Collectible',
        'Winged Glassversarial',
        'Witek Radomski',
        'Juan Benet',
        'Brandon Ramirez',
        'Vogelsteller',
        '20 Years of SF Dance Music DOSC Audio NFT',
        '20 Years of SF Dance Music J-Kind Audio NFT',
      ],
      issueIndex: 'Issue Four',
      url: [
        '/images/nft/4/exc/Untitled (3) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        '/images/nft/4/semi/bomber_digitalax.mp4',
        '/images/nft/4/exc/W3FW-GIF.gif',
        '/images/nft/4/semi/web3boy_allProtocols.mp4',
        '/images/nft/4/common/web3girl_allProtocols (1).mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/exc/Witek.png',
        '/images/nft/4/exc/Juan Benet.png',
        '/images/nft/4/exc/Brandon.png',
        '/images/nft/4/exc/Fabian.png',
        '/images/nft/4/exc/Nesting Berlin (6mins 39secs).mp4',
        '/images/nft/4/exc/jkind.mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatUntitled (3).mp4emakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket + Digital Fashion 3D Collectible + Physical W3FW Jacket, Web3 DeFi Fashion Male and Female Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music DOSC and JKind Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.',
        'Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and match it with the DRIP physical IRL varsity jacket version!',
        'Unlock the 3D modeled digital fashion W3FW Bomber Jacket version of your Decentraland Skin! A high fidelity version to showcase your style.',
        'Match your Decentraland In-Game Skin and 3D digital Bomber Jacket Collectible with an IRL Physical Varsity Jacket. Make sure you are signed in at purchase in order to receive the DRIP email on how to claim your physical jacket and have it shipped to you across the realms!',
        'A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.',
        'A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.',
        'The first glass-winged XENOTECH garment.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.',
        'Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Hailing from San Francisco, Dosc (Jason Urbina) is creating his artistic foothold in the dance music industry by blending genre-specific sounds to produce tracks that unite divisions of music.',
        'Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. J-KIND is a DJ/Producer residing in San Francisco Bay Area of California. His diverse and eclectic style transcends many genres and is currently focused on his burning passion for techno.',
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 13,
      title: 'Common Unlock',
      subTitle: [
        'Issue Three',
        'Metallic Bubblegum',
        'Infinite Zayman',
        'Wear to DeFi Cap',
        'LED XENO Shirt',
        'Chrome Ziva',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/common/moshed-07-09-23-50-48.mp4',
        '/images/nft/3/common/Metallic Bubblegum.png',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/common/Untitled (2) (1).mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        "Captain America's pink shield is a really special item as it was the key for me to start making 3D. This was my first object made in Blender. So many great memories! I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.",
        'Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.',
        'WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your cap through DRIP and choose between one of many DeFi caps with staking functionality.',
        'This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.',
        'The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.',
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 14,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Three',
        'Infinite Zayman',
        'Omega',
        'Wear to DeFi Hoodie',
        'LED XENO Shirt',
        'Chrome Ziva',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/semi/moshed-07-09-23-46-36.mp4',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/semi/Omega.png',
        '/images/nft/3/semi/Untitled (3) (1).mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.',
        "The texture, appearance and colors were accidentally replaced. Glad that the final render turned out ok and I am very happy to have it now as an NFT. It deserves this on-chain immutability! I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.",
        'WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your hoodie through DRIP and choose between one of many DeFi hoodies with staking functionality.',
        'This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.',
        'The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.',
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 15,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Three',
        'Infinite Zayman',
        'Wear to DeFi Cap',
        'Wear to DeFi Hoodie',
        'Alpha',
        'LED XENO Shirt',
        'Chrome Ziva',
        'Stani',
        'Kain',
        'Andre',
        'Rune',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/exc/moshed-07-09-23-29-30.mp4',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/common/Untitled (2) (1).mp4',
        '/images/nft/3/semi/Untitled (3) (1).mp4',
        '/images/nft/3/exc/Alpha.mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
        '/images/nft/3/exc/Stani.png',
        '/images/nft/3/exc/Kain.png',
        '/images/nft/3/exc/Andre.png',
        '/images/nft/3/exc/Rune.png',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Web3 Wizards collectible series, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        'Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.',
        'WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your cap through DRIP and choose between one of many DeFi caps with staking functionality. ',
        'WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your hoodie through DRIP and choose between one of many DeFi hoodies with staking functionality.',
        "This token is a portal that was just waiting to turn into an NFT. Now your powers have increased. I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.",
        'This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.',
        'The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.',
        'To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.',
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 9,
      title: 'Common Unlock',
      subTitle: [
        'Issue Two',
        'PORTAL',
        'Edge Outfit',
        'MC OG 1.5',
        'Wear Your Values HRF Leap of Faith: Courage',
        'Minecraft Guild Hoodie Orange',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/common/moshed-06-11-5-3-53.mp4',
        '/images/nft/2/common/1080p (1).MOV',
        '/images/nft/2/common/Digitalax_02.mp4',
        '/images/nft/2/common/espa_skin (1).mp4',
        '/images/nft/2/common/Untitled.mp4',
        '/images/nft/2/common/MC-Gif (1).gif',
        '/images/nft/2/common/IMG_202105281404040 (3).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        "9EN travels through different dimensions, virtual realms, and eventually makes it to Earth. A portal she uses through hyperspace travel is a symbol portrayed in this particular NFT. The symbol tends to stretch out due to a gravitational singularity in which there's a chaotic oscillation of the stretching and squeezing of space during an interstellar journey. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.",
        "This outfit stands out for its angular and metallic lines. It's a flashy evening urban style. The jacket is semi-rigid and the trousers are sporty. On the trousers there are two bands that recall the jacket's details. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.",
        "A one of its kind Minecraft digital fashion skin designed by a dude that's been at the heart of the game for more than a decade. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network. ",
        'The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.',
        'Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz',
        'The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.',
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 10,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Two',
        'SEE',
        'Porka Jacket',
        'Wear Your Values HRF Leap of Faith: All In',
        'Polaris X35 Suit',
        'Minecraft Guild Hoodie Green',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/semi/moshed-06-11-5-12-59.mp4',
        '/images/nft/2/semi/Video_1 (2).MOV',
        '/images/nft/2/semi/Untitled (3).png',
        '/images/nft/2/semi/Untitled (1).mp4',
        '/images/nft/2/semi/Polaris-suit-x35-digitalax.png',
        '/images/nft/2/semi/MC-Gif (1) copy 2.gif',
        '/images/nft/2/semi/IMG_202105281404040 (3).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.',
        "9EN is seen to be approaching a symbol she's curious to know more about. Her first encounter with the symbol feels like a magnetic effect that's pulling her closer and closer. She enters the portal. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.",
        'Designed by Nicole Savitskaya, a talented digital fashion designer from Ukraine and the founder of porka_x. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.',
        'The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.',
        'Designed by Mia Locklace and modeled by Sarah Reikka, a French Canadian virtual influencer & model. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.',
        'Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/',
        'The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.',
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 11,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Two',
        'Wear Your Values HRF Leap of Faith: Cross Over',
        'SAVAGE',
        'Welcome to the Meta-Jungle',
        'Lumps',
        'Minecraft Guild Hoodie Purple',
        'Alex Beregszaszi',
        'Pooja Ranjan',
        'Abdelhamid Bakhta',
        'Tim Beiko',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/exc/moshed-06-11-5-24-5.mp4',
        '/images/nft/2/exc/Untitled (2).mp4',
        '/images/nft/2/exc/720p.MOV',
        '/images/nft/2/exc/BladeRunway Final Render HD (1).png',
        '/images/nft/2/exc/Animation.mp4',
        '/images/nft/2/exc/MC-Gif (1) copy.gif',
        '/images/nft/2/exc/Alex (1).png',
        '/images/nft/2/exc/Pooja (1).png',
        '/images/nft/2/exc/Abdel Hamid (1).png',
        '/images/nft/2/exc/Tim Beiko (1).png',
        '/images/nft/2/exc/IMG_202105281404040 (2).mp4',
      ],
      body: [
        'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content, Web3 Wizards collectible series + access to unlockable magazine content pages.',
        'The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.',
        "When 9EN is traveling through the virtual realms of the Earth she stumbles upon a song called 'Savage' by Megan Thee Stallion. This NFT presents a tunnel trip featuring 'Savage' remixed by 9EN. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.",
        'Blade Runway is the first Digital Couture Fashion House in Italy. Founded by designers Greta Meacci and Alan Aronica, the project was launched to bring the high quality and know-how of traditional Italian haute couture into the digital world. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.',
        "Lumps is a wearable living creature. She was created on a different planet using the natural resources from this planet's environment. Similar to how a plant on earth is an actual living organism, the plants on this planet are alive and possess different capabilities. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.",
        'Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/',
        'To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.',
        'To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.',
        'To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.',
        'To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.',
        'The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.',
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 1,
      title: 'Common Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/common/Untitled (24).mp4',
        '/images/nft/1/common/Untitled (20).mp4',
        '/images/nft/1/common/gamer-girl.jpg',
        '/images/nft/1/common/Project Name (2).mp4',
        '/images/nft/1/common/Untitled (2).mp4',
        '/images/nft/1/common/Untitled (28).mp4',
      ],
      body: 'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl gamer trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion jewellery collectible, electronic bass audio tune from top San Francisco based music artist Singe, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.',
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 2,
      title: 'Semi-Rare Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/semi/Untitled (23).mp4',
        '/images/nft/1/semi/Untitled (21).mp4',
        '/images/nft/1/semi/Angel-with-rose.jpg',
        '/images/nft/1/semi/Project Name (1).mp4',
        '/images/nft/1/semi/Untitled (4).mp4',
        '/images/nft/1/semi/Untitled (27).mp4',
        '/images/nft/1/semi/1.gif',
      ],
      body: 'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl angel trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible male outfit, melodic audio  tune from top San Francisco based DJ J-Kind, physical DIGITALAX DRIP fashion item with on-chain utility, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.',
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 3,
      title: 'Exclusive Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/exc/Untitled (25).mp4',
        '/images/nft/1/exc/Cameron (1).png',
        '/images/nft/1/exc/girl-and-panda.png',
        '/images/nft/1/exc/HARUTO (1).png',
        '/images/nft/1/exc/James (1).png',
        '/images/nft/1/exc/Project Name (3).mp4',
        '/images/nft/1/exc/Untitled (15).mp4',
        '/images/nft/1/exc/VICtor.png',
        '/images/nft/1/exc/3.gif',
        '/images/nft/1/exc/Untitled (26).mp4',
      ],
      body: 'DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl rare trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible female outfit, synth audio tune from renowned San Francisco based music veteran Gregory Gordon, physical DIGITALAX DRIP fashion item with on-chain utility, Web3 Wizards Genesis collection, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.',
      price: 2,
      amountAvailable: 50,
    },
  ],
];

export const info = [
  {
    image: '/images/nft/6/main.png',
    id: 'SIX',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/5/main.png',
    id: 'FIVE',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/4/main.png',
    id: 'FOUR',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/3/main.png',
    id: 'THREE',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/2/home.png',
    id: 'TWO',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/1/main_magazine.png',
    id: 'ONE',
    title: 'DIGIFIZZY',
  },
];
