export const details = [
  [
    {
      id: 21,
      title: 'Common Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        '20 Years of SF Dance Music Christopher Leath Audio NFT',
        '20 Years of SF Dance Music Paul Leath Audio NFT',
        'Winged Glassversarial',
        'Web3 DeFi Fashion Female Collectible',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/4/common/Untitled (1) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        'http://digitalax.mypinata.cloud/ipfs/QmZeabmF7EhDnJVHShD8Wgk5zBxNopGsWNU1NyW4qoAvmy',
        '/images/nft/4/common/mindmeld.mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/common/web3girl_allProtocols (1).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket, Web3 DeFi Fashion Female Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music Christopher and Paul Leath Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.`,
        `Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and head over to DRIP to purchase the physical varsity jacket version to rep IRL!`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Christopher Leach aka el gato #9 is a DJ/Producer of various genres Electronic - Techno, DnB, House, Dub, Down-tempo, Dancehall, Ambient, and Experimental.`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Paul Leath has taken on several roles with his involvement in the electronic community, promoter, agent, manager and record distribution. During this entire span, always producing and deejaying.`,
        `The first glass-winged XENOTECH garment.`,
        `A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.`,
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 22,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        'Collectible 3D Digital Fashion W3FW Bomber Jacket',
        'Web3 DeFi Fashion Male Collectible',
        'Winged Glassversarial',
        '20 Years of SF Dance Music Arturo Mood Audio NFT',
        '20 Years of SF Dance Music Arturo Communication NFT',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/4/semi/Untitled (2) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        '/images/nft/4/semi/bomber_digitalax.mp4',
        '/images/nft/4/semi/web3boy_allProtocols.mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/semi/Arturo Garces - Mood.mp4',
        '/images/nft/4/semi/Arturo Garces - Communication.mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket + Digital Fashion 3D Collectible, Web3 DeFi Fashion Male Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music Arturo Garces Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.`,
        `Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and head over to DRIP to purchase the physical varsity jacket version to rep IRL!`,
        `Unlock the 3D modeled digital fashion W3FW Bomber Jacket version of your Decentraland Skin! A high fidelity version to showcase your style.`,
        `A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.`,
        `The first glass-winged XENOTECH garment.`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Arturo's music has helped define the unique and emerging Silicon Valley sound. This approach blends the driving, beat-laden beauty of techno with the soulful, deep melodies of house.`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Arturo's music has helped define the unique and emerging Silicon Valley sound. This approach blends the driving, beat-laden beauty of techno with the soulful, deep melodies of house.`,
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 24,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Four',
        'The First Dungeon Unique PFP In-Game Character',
        'Decentraland In-Game W3FW Bomber Jacket',
        'Collectible 3D Digital Fashion W3FW Bomber Jacket',
        'Physical W3FW Varsity Bomber Jacket',
        'Web3 DeFi Fashion Male Collectible',
        'Web3 DeFi Fashion Female Collectible',
        'Winged Glassversarial',
        'Witek Radomski',
        'Juan Benet',
        'Brandon Ramirez',
        'Vogelsteller',
        '20 Years of SF Dance Music DOSC Audio NFT',
        '20 Years of SF Dance Music J-Kind Audio NFT',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/4/exc/Untitled (3) (2).mp4',
        '/images/nft/4/common/Untitled video (2).mp4',
        '/images/nft/4/common/Untitled video (4).mp4',
        '/images/nft/4/semi/bomber_digitalax.mp4',
        '/images/nft/4/exc/W3FW-GIF.gif',
        '/images/nft/4/semi/web3boy_allProtocols.mp4',
        '/images/nft/4/common/web3girl_allProtocols (1).mp4',
        '/images/nft/4/common/Winged_Glassversarial (1).mp4',
        '/images/nft/4/exc/Witek.png',
        '/images/nft/4/exc/Juan Benet.png',
        '/images/nft/4/exc/Brandon.png',
        '/images/nft/4/exc/Fabian.png',
        '/images/nft/4/exc/Nesting Berlin (6mins 39secs).mp4',
        '/images/nft/4/exc/jkind.mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatUntitled (3).mp4emakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; W3FW Varsity Digital Fashion Decentraland Bomber Jacket + Digital Fashion 3D Collectible + Physical W3FW Jacket, Web3 DeFi Fashion Male and Female Collectible, The First Dungeon Unique In-Game Pixel Character and PFP, 20 years of San Francisco Dance Music DOSC and JKind Audio NFTs, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `The First Dungeon— an open source 2D battle royale game developed by Thijmen Happy. The game is launching through DIGITALAX’s ESPA esports platform mid September. Take your unique character in-game to engage in The First Dungeon casual esports battles, rank on the leaderboard and earn $MONA as you level up from 0 to 1. Also take your little character across the web as an online 2D pixel art identity marker.`,
        `Exclusive W3FW Decentraland In-Game Digital Fashion Memorabilia Bomber Jacket! View it also through the DressX AR Try On filter and match it with the DRIP physical IRL varsity jacket version!`,
        `Unlock the 3D modeled digital fashion W3FW Bomber Jacket version of your Decentraland Skin! A high fidelity version to showcase your style.`,
        `Match your Decentraland In-Game Skin and 3D digital Bomber Jacket Collectible with an IRL Physical Varsity Jacket. Make sure you are signed in at purchase in order to receive the DRIP email on how to claim your physical jacket and have it shipped to you across the realms!`,
        `A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.`,
        `A high fidelity Web3 Digital Fashion x DeFi collectible. Stride in style as you wear to earn and mix look with liquidity.`,
        `The first glass-winged XENOTECH garment.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we are attributing those that set the standards for defining DeCo as we experience it today and for the future. The DeCo Definers.`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. Hailing from San Francisco, Dosc (Jason Urbina) is creating his artistic foothold in the dance music industry by blending genre-specific sounds to produce tracks that unite divisions of music.`,
        `Nearly everyone who has regularly gone out in San Francisco over the last twenty years has seen, heard, and been moved by waves of change in some ways very different from all the others that came before. 5 top SF DJs and Musicians are combining forces for a collective ensemble release with DIGIFIZZY. Taking those tunes to the digi base. J-KIND is a DJ/Producer residing in San Francisco Bay Area of California. His diverse and eclectic style transcends many genres and is currently focused on his burning passion for techno.`,
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 13,
      title: 'Common Unlock',
      subTitle: [
        'Issue Three',
        'Metallic Bubblegum',
        'Infinite Zayman',
        'Wear to DeFi Cap',
        'LED XENO Shirt',
        'Chrome Ziva',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/common/moshed-07-09-23-50-48.mp4',
        '/images/nft/3/common/Metallic Bubblegum.png',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/common/Untitled (2) (1).mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `Captain America's pink shield is a really special item as it was the key for me to start making 3D. This was my first object made in Blender. So many great memories! I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.`,
        `Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.`,
        `WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your cap through DRIP and choose between one of many DeFi caps with staking functionality.`,
        `This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.`,
        `The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.`,
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 14,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Three',
        'Infinite Zayman',
        'Omega',
        'Wear to DeFi Hoodie',
        'LED XENO Shirt',
        'Chrome Ziva',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/semi/moshed-07-09-23-46-36.mp4',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/semi/Omega.png',
        '/images/nft/3/semi/Untitled (3) (1).mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.`,
        `The texture, appearance and colors were accidentally replaced. Glad that the final render turned out ok and I am very happy to have it now as an NFT. It deserves this on-chain immutability! I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.`,
        `WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your hoodie through DRIP and choose between one of many DeFi hoodies with staking functionality.`,
        `This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.`,
        `The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.`,
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 15,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Three',
        'Infinite Zayman',
        'Wear to DeFi Cap',
        'Wear to DeFi Hoodie',
        'Alpha',
        'LED XENO Shirt',
        'Chrome Ziva',
        'Stani',
        'Kain',
        'Andre',
        'Rune',
      ],
      issueIndex: 'Issue Three',
      url: [
        '/images/nft/3/exc/moshed-07-09-23-29-30.mp4',
        '/images/nft/3/common/Untitled (6).mp4',
        '/images/nft/3/common/Untitled (2) (1).mp4',
        '/images/nft/3/semi/Untitled (3) (1).mp4',
        '/images/nft/3/exc/Alpha.mp4',
        '/images/nft/3/common/0001-0600-1.m4v',
        '/images/nft/3/common/Untitled (1) (1).mp4',
        '/images/nft/3/exc/Stani.png',
        '/images/nft/3/exc/Kain.png',
        '/images/nft/3/exc/Andre.png',
        '/images/nft/3/exc/Rune.png',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; VR audio visual NFT by Anna Chilli, ABigNeonGlitter 3D Art collectibles, Exclusive DeFi DRIP Hoodies with NFT staking, Web3 Wizards collectible series, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `Anna Chili is a visual artist/entrepreneur/art shaman/ muralist/3d VR digital artist who lives in the San Francisco Bay Area. She is originally from Odessa, Ukraine. Infinite Zayman is a trip into her world.`,
        `WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your cap through DRIP and choose between one of many DeFi caps with staking functionality. `,
        `WTF is DeFi and why is it so hard to use? What if you could earn more from what you wear? DIGITALAX and the Global Designer Network DAO have partnered with top DeFi protocols creating hybrid digital-physical NFT fashion collections with DeFi functionality. This fashion isn’t just ordinary fashion. It onboards you into an entire world of NFTs, Decentralised Finance, Crypto and Web3. Every fashion piece is a unique NFT that can also earn you yield in $MONA token and other crypto. We are melting the centralised exploitative crown to weave the fabric of a generative ecosystem. Make sure to be signed in on purchase to claim your hoodie through DRIP and choose between one of many DeFi hoodies with staking functionality.`,
        `This token is a portal that was just waiting to turn into an NFT. Now your powers have increased. I always loved collecting; from holographic cards that came greasy in snack packages, to video-game tapes, toys, action figures, cups, magazines, phone cards… and I could name more. Oh the 90s! Today I am very excited about Non-Fungible Tokens and designing them to literally carry my traits around as a kind of rich information like DNA. At any time I can organize a collection and make these gems available for other digital hunters. I'm feeling so ready for this! ABigNeonGlitter is a 3D digital designer and part of the Global Designer Network.`,
        `This is a clear LED XENOTECH shirt. Fabrics used include clear digital vinyl, LED fabric, and video fabric.`,
        `The first of an upcoming collection of 12 designs, this design is inspired by activewear. Playing with fluid textures and fitted silhouettes Chrome Ziva reminds me of the strength of women.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.`,
        `To pay homage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characterisations; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this edition we take our hats off to those that pioneered DeFi before anyone really even knew what it was. These are the DeFi Dealers.`,
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 9,
      title: 'Common Unlock',
      subTitle: [
        'Issue Two',
        'PORTAL',
        'Edge Outfit',
        'MC OG 1.5',
        'Wear Your Values HRF Leap of Faith: Courage',
        'Minecraft Guild Hoodie Orange',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/common/moshed-06-11-5-3-53.mp4',
        '/images/nft/2/common/1080p (1).MOV',
        '/images/nft/2/common/Digitalax_02.mp4',
        '/images/nft/2/common/espa_skin (1).mp4',
        '/images/nft/2/common/Untitled.mp4',
        '/images/nft/2/common/MC-Gif (1).gif',
        '/images/nft/2/common/IMG_202105281404040 (3).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `9EN travels through different dimensions, virtual realms, and eventually makes it to Earth. A portal she uses through hyperspace travel is a symbol portrayed in this particular NFT. The symbol tends to stretch out due to a gravitational singularity in which there's a chaotic oscillation of the stretching and squeezing of space during an interstellar journey. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `This outfit stands out for its angular and metallic lines. It's a flashy evening urban style. The jacket is semi-rigid and the trousers are sporty. On the trousers there are two bands that recall the jacket's details. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `A one of its kind Minecraft digital fashion skin designed by a dude that's been at the heart of the game for more than a decade. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network. `,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 10,
      title: 'Semi-Rare Unlock',
      subTitle: [
        'Issue Two',
        'SEE',
        'Porka Jacket',
        'Wear Your Values HRF Leap of Faith: All In',
        'Polaris X35 Suit',
        'Minecraft Guild Hoodie Green',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/semi/moshed-06-11-5-12-59.mp4',
        '/images/nft/2/semi/Video_1 (2).MOV',
        '/images/nft/2/semi/Untitled (3).png',
        '/images/nft/2/semi/Untitled (1).mp4',
        '/images/nft/2/semi/Polaris-suit-x35-digitalax.png',
        '/images/nft/2/semi/MC-Gif (1) copy 2.gif',
        '/images/nft/2/semi/IMG_202105281404040 (3).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
        `9EN is seen to be approaching a symbol she's curious to know more about. Her first encounter with the symbol feels like a magnetic effect that's pulling her closer and closer. She enters the portal. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `Designed by Nicole Savitskaya, a talented digital fashion designer from Ukraine and the founder of porka_x. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `Designed by Mia Locklace and modeled by Sarah Reikka, a French Canadian virtual influencer & model. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 11,
      title: 'Exclusive Unlock',
      subTitle: [
        'Issue Two',
        'Wear Your Values HRF Leap of Faith: Cross Over',
        'SAVAGE',
        'Welcome to the Meta-Jungle',
        'Lumps',
        'Minecraft Guild Hoodie Purple',
        'Alex Beregszaszi',
        'Pooja Ranjan',
        'Abdelhamid Bakhta',
        'Tim Beiko',
        'PRIZEKICK',
      ],
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/exc/moshed-06-11-5-24-5.mp4',
        '/images/nft/2/exc/Untitled (2).mp4',
        '/images/nft/2/exc/720p.MOV',
        '/images/nft/2/exc/BladeRunway Final Render HD (1).png',
        '/images/nft/2/exc/Animation.mp4',
        '/images/nft/2/exc/MC-Gif (1) copy.gif',
        '/images/nft/2/exc/Alex (1).png',
        '/images/nft/2/exc/Pooja (1).png',
        '/images/nft/2/exc/Abdel Hamid (1).png',
        '/images/nft/2/exc/Tim Beiko (1).png',
        '/images/nft/2/exc/IMG_202105281404040 (2).mp4',
      ],
      body: [
        `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content, Web3 Wizards collectible series + access to unlockable magazine content pages.`,
        `The Wear Your Values campaign brings voice to both the exploitation, tyranny and oppression of workers along the supply chain, unseen Creators and more broadly highlighting the power of Fashion throughout all of this. The Human Rights Foundation is collaborating with DIGITALAX and Maria Ruano to draw attention to human rights concerns in closed societies, voice the importance of a globally transparent supply chain and bridge the Digi-Fizzy (Digital-Physical) realms for promoting positive compounding action & distributed content generation native to movements for social & economic change. The 3D glitched digital fashion scene highlights the tension between the cross over from the physical to the digital and how Creators of all kinds summon the courage to leap into the unknown and take a stance against exploitation.`,
        `When 9EN is traveling through the virtual realms of the Earth she stumbles upon a song called 'Savage' by Megan Thee Stallion. This NFT presents a tunnel trip featuring 'Savage' remixed by 9EN. 9EN (short for 9EN3TRIX) is the world’s first virtual DJ, Music Producer - artist.`,
        `Blade Runway is the first Digital Couture Fashion House in Italy. Founded by designers Greta Meacci and Alan Aronica, the project was launched to bring the high quality and know-how of traditional Italian haute couture into the digital world. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Lumps is a wearable living creature. She was created on a different planet using the natural resources from this planet's environment. Similar to how a plant on earth is an actual living organism, the plants on this planet are alive and possess different capabilities. DIGITALAX ran its first open digital fashion competition bringing together amazingly talented creators from across the realms, focused on enabling creatives for modding their version of the metaverse. The content champions of the competition have been included in the DIGIFIZZY content bundles, where buyers will also receive in-game ESPA compatible versions of these skins during the next ESPA esports launch, all hand-crafted in-house through the Global Designer Network.`,
        `Crossing over the digi-fizzy realms with the Minecraft Guild Hoodie. REP your tribe IRL and battle Herobrine in the ESPA casual esports tournaments as your hoodie unlocks ESPA XP for leveling up with $MONA. See more of what your physical item unlocks at https://drip.digitalax.xyz/`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `To pay homeage to the often overlooked lionhearts within the web3 community— the devs— we are introducing Web3 Wizards; an ongoing series of on-chain NFT web3 dev characteristaions; spotlighting new devs every issue, all designed and minted in-house by DIGITALAX. For this collection we are recognising some of the core contributors and front runners of EIP-1559— perhaps one of the most important economical updates for the entirety of Ethereum’s future and setting the ecosystem up for even more adoption success.`,
        `The first XENOTECH Shoe—the kind that would be worn by an esoteric Extended Reality Architect in XENO City.`,
      ],
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      id: 1,
      title: 'Common Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/common/Untitled (24).mp4',
        '/images/nft/1/common/Untitled (20).mp4',
        '/images/nft/1/common/gamer-girl.jpg',
        '/images/nft/1/common/Project Name (2).mp4',
        '/images/nft/1/common/Untitled (2).mp4',
        '/images/nft/1/common/Untitled (28).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl gamer trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion jewellery collectible, electronic bass audio tune from top San Francisco based music artist Singe, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 0.5,
      amountAvailable: 700,
    },
    {
      id: 2,
      title: 'Semi-Rare Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/semi/Untitled (23).mp4',
        '/images/nft/1/semi/Untitled (21).mp4',
        '/images/nft/1/semi/Angel-with-rose.jpg',
        '/images/nft/1/semi/Project Name (1).mp4',
        '/images/nft/1/semi/Untitled (4).mp4',
        '/images/nft/1/semi/Untitled (27).mp4',
        '/images/nft/1/semi/1.gif',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl angel trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible male outfit, melodic audio  tune from top San Francisco based DJ J-Kind, physical DIGITALAX DRIP fashion item with on-chain utility, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 1,
      amountAvailable: 200,
    },
    {
      id: 3,
      title: 'Exclusive Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/exc/Untitled (25).mp4',
        '/images/nft/1/exc/Cameron (1).png',
        '/images/nft/1/exc/girl-and-panda.png',
        '/images/nft/1/exc/HARUTO (1).png',
        '/images/nft/1/exc/James (1).png',
        '/images/nft/1/exc/Project Name (3).mp4',
        '/images/nft/1/exc/Untitled (15).mp4',
        '/images/nft/1/exc/VICtor.png',
        '/images/nft/1/exc/3.gif',
        '/images/nft/1/exc/Untitled (26).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl rare trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible female outfit, synth audio tune from renowned San Francisco based music veteran Gregory Gordon, physical DIGITALAX DRIP fashion item with on-chain utility, Web3 Wizards Genesis collection, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 2,
      amountAvailable: 50,
    },
  ],
];

export const info = [
  {
    image: '/images/nft/4/main.png',
    id: 'FOUR',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/3/main.png',
    id: 'THREE',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/2/home.png',
    id: 'TWO',
    title: 'DIGIFIZZY',
  },
  {
    image: '/images/nft/1/main_magazine.png',
    id: 'ONE',
    title: 'DIGIFIZZY',
  },
];
