const details = [
  [
    {
      title: 'Common Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/common/Untitled (24).mp4',
        '/images/nft/1/common/Untitled (20).mp4',
        '/images/nft/1/common/gamer-girl.jpg',
        '/images/nft/1/common/Project Name (2).mp4',
        '/images/nft/1/common/Untitled (2).mp4',
        '/images/nft/1/common/Untitled (28).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl gamer trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion jewellery collectible, electronic bass audio tune from top San Francisco based music artist Singe, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 0.5,
      amountAvailable: 700,
    },
    {
      title: 'Semi-Rare Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/semi/Untitled (23).mp4',
        '/images/nft/1/semi/Untitled (21).mp4',
        '/images/nft/1/semi/Angel-with-rose.jpg',
        '/images/nft/1/semi/Project Name (1).mp4',
        '/images/nft/1/semi/Untitled (4).mp4',
        '/images/nft/1/semi/Untitled (27).mp4',
        '/images/nft/1/semi/1.gif',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl angel trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible male outfit, melodic audio  tune from top San Francisco based DJ J-Kind, physical DIGITALAX DRIP fashion item with on-chain utility, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 1,
      amountAvailable: 200,
    },
    {
      title: 'Exclusive Unlock',
      issueIndex: 'Issue One',
      url: [
        '/images/nft/1/exc/Untitled (25).mp4',
        '/images/nft/1/exc/Cameron (1).png',
        '/images/nft/1/exc/girl-and-panda.png',
        '/images/nft/1/exc/HARUTO (1).png',
        '/images/nft/1/exc/James (1).png',
        '/images/nft/1/exc/Project Name (3).mp4',
        '/images/nft/1/exc/Untitled (15).mp4',
        '/images/nft/1/exc/VICtor.png',
        '/images/nft/1/exc/3.gif',
        '/images/nft/1/exc/Untitled (26).mp4',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Tenshi Girl rare trading card, ESPA in-game cyber minecraft skin, first traditional Indian digital fashion collectible female outfit, synth audio tune from renowned San Francisco based music veteran Gregory Gordon, physical DIGITALAX DRIP fashion item with on-chain utility, Web3 Wizards Genesis collection, a unique 3D modeled artwork by collaborative project HYPERREAALIYAH + HIDDEN content and additional NFT airdrops! We are here to mod the metaverse.`,
      price: 2,
      amountAvailable: 50,
    },
  ],
  [
    {
      title: 'Common Unlock',
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/common/moshed-06-11-5-3-53.mp4',
        '/images/nft/2/common/1080p (1).MOV',
        '/images/nft/2/common/Digitalax_02.mp4',
        '/images/nft/2/common/espa_skin (1).mp4',
        '/images/nft/2/common/Untitled.mp4',
        '/images/nft/2/common/IMG_202105281404040 (3).mp4',
        '/images/nft/2/common/MC-Gif (1).gif',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the common unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
      price: 0.5,
      amountAvailable: 700,
    },
    {
      title: 'Semi-Rare Unlock',
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/semi/moshed-06-11-5-12-59.mp4',
        '/images/nft/2/semi/Untitled (1).mp4',
        '/images/nft/2/semi/IMG_202105281404040 (3).mp4',
        '/images/nft/2/semi/MC-Gif (1) copy 2.gif',
        '/images/nft/2/semi/Polaris-suit-x35-digitalax.png',
        '/images/nft/2/semi/Untitled (3).png',
        '/images/nft/2/semi/Video_1 (2).MOV',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the semi-rare unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content + access to unlockable magazine content pages.`,
      price: 1,
      amountAvailable: 200,
    },
    {
      title: 'Exclusive Unlock',
      issueIndex: 'Issue Two',
      url: [
        '/images/nft/2/exc/moshed-06-11-5-24-5.mp4',
        '/images/nft/2/exc/720p.MOV',
        '/images/nft/2/exc/Abdel Hamid (1).png',
        '/images/nft/2/exc/Alex (1).png',
        '/images/nft/2/exc/Animation.mp4',
        '/images/nft/2/exc/BladeRunway Final Render HD (1).png',
        '/images/nft/2/exc/Untitled (2).mp4',
        '/images/nft/2/exc/IMG_202105281404040 (2).mp4',
        '/images/nft/2/exc/MC-Gif (1) copy.gif',
        '/images/nft/2/exc/Pooja (1).png',
        '/images/nft/2/exc/Tim Beiko (1).png',
      ],
      body: `DIGIFIZZY is the first of its kind. It’s architected for the metaverse, bringing together creators, anarchists, risk takers and dreamers across web3, fashion, gaming, art, music, crypto and NFTs, to prove out a completely new publishing distribution model. DIGIFIZZY is for the gatemakers. For the exclusive unlockable ERC-998 bundle you can burn your 721 NFT to receive 1155 NFT treasures; Digital Fashion Flex Your Flare collections, 9EN AI Robot Visual Audio piece, DRIP Minecraft Guild Physical Hoodie, Human Rights Foundation Wear Your Values Fashion scene collectible, Deco Only Fans behind the scenes content, Web3 Wizards collectible series + access to unlockable magazine content pages.`,
      price: 2,
      amountAvailable: 50,
    },
  ],
];

export default details;
