import React from 'react'
import styles from './page5354.module.scss'

const Page5354 = () => {
  return (
    <div className={styles.wrapper}>
      <video autoPlay muted loop className={styles.video1}>
        <source src='./magazine/1/videos/moshed-05-02-1-15-28.mp4' type='video/mp4' />
      </video>

      <img className={styles.image1} src='./magazine/4/images/5354_image1.png' />

      <div className={styles.text1}>
        PHILLIPINES
      </div>
      <div className={styles.text2}>
        INTERNATIONAL PLAYERS
      </div>

      <img className={styles.image2} src='./magazine/4/images/5354_image2.png' />
      

      <div className={styles.text3}>
        PLAY  TO EARN ECONOMY 
      </div>
      <div className={styles.text4}>
        INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS
      </div>
      <div className={styles.text5}>
        INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS
      </div>
      <div className={styles.text6}>
        INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS
      </div>
      <div className={styles.text7}>
        INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL
      </div>

      <img className={styles.image3} src='./magazine/4/images/5354_image3.png' />
    </div>
  )
}

export default Page5354
