import React from 'react'
import styles from './page48.module.scss'

const Page48 = () => {
  return (
    <div className={styles.wrapper}>
      <img className={styles.image1} src='/magazine/4/images/5354_image2_mobile.png' />
      <h1>
        PLAY TO<br />EARN<br />ECONOMY
      </h1>
      <h2>
        INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERS INTERNATIONAL PLAYERSINTERNATIONAL PLAYERSINTERNATIONAL PLAYERS
      </h2>
    </div>
  )
}

export default Page48